### ISSUE TITLE
Decide how/if to include a MATLAB environment

### ISSUE THREAD

**Issue by aplowman** [hpcflow/matflow-environments#2]
Interesting discussion [here](https://github.com/matlab-actions/setup-matlab/issues/18) about using MATLAB in GitHub Actions. It seems that running a MATLAB script in GitHub Actions does not require a license to be specified, but running the MATLAB compiler does.

Separately: it seems that once a MATLAB script has been compiled, a licence is not required by the end-user (just the MATLAB runtime).

**Comment by Gbowker** [comment]
Any progress on this? Currently we're using a hodgepodge of an environment at UoM to be able to use MTEX in matflow:
```yaml
- name: matlab_env
  setup: |
    module load apps/binapps/matlab/R2024b
    MTEX_DIR=/mnt/eps01-rds/Fonseca-Lightform/shared/software/mtex/mtex-6.1.0/
  executables:
  - label: run_mtex
    instances:
    - command: |
          for dir in $(find ${MTEX_DIR} -type d | grep -v -e ".git" -e "@" -e "private"); do MATLABPATH="${dir};${MATLABPATH}"; d>
          export MATLABPATH=${MATLABPATH}
          matlab -softwareopengl -singleCompThread -batch "addpath('<<script_dir>>'); <<script_name_no_ext>> <<args>>"
      num_cores: 1
      parallel_mode: null
  - label: compile_mtex
    instances:
    - command: |
        for dir in $(find ${MTEX_DIR} -type d | grep -v -e ".git" -e "@" -e "private" -e "data" -e "makeDoc" -e "templates" -e "n>
        do
          MTEX_INCLUDE="-I ${dir} ${MTEX_INCLUDE}"
        done
        export MTEX_INCLUDE="${MTEX_INCLUDE} -a ${MTEX_DIR}/data -a ${MTEX_DIR}/plotting/plotting_tools/colors.mat"
        mcc -R -singleCompThread -R -softwareopengl -m "<<script_path>>" <<args>> -o matlab_exe ${MTEX_INCLUDE}
      num_cores: 1
      parallel_mode: null
  - label: run_compiled_mtex
    instances:
    - command: |
        export MATLAB_RUNTIME=/full/path/to/matlab/runtime-or-installation
        ./run_matlab_exe.sh ${MATLAB_RUNTIME} <<args>>
      num_cores: 1
      parallel_mode: null
```
